// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarBox: typeof import('./src/components/BarBox.vue')['default']
    FooterControls: typeof import('./src/components/FooterControls.vue')['default']
    GoalBar: typeof import('./src/components/GoalBar.vue')['default']
    LittleInput: typeof import('./src/components/LittleInput.vue')['default']
    RestBar: typeof import('./src/components/RestBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimerHeader: typeof import('./src/components/TimerHeader.vue')['default']
    WorkBar: typeof import('./src/components/WorkBar.vue')['default']
  }
}

export {}
