// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimerBar: typeof import('./src/components/TimerBar.vue')['default']
    TimerHeader: typeof import('./src/components/TimerHeader.vue')['default']
  }
}

export {}
